# Generated by Django 2.0.2 on 2018-02-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caselog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(blank=True, max_length=200, null=True)),
                ('orgnization', models.CharField(blank=True, max_length=200, null=True)),
                ('problem', models.CharField(blank=True, max_length=200, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
