# Generated by Django 2.0.2 on 2018-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
