# Generated by Django 2.0.2 on 2018-02-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_caselog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselog',
            name='handleby',
            field=models.CharField(choices=[('A', 'Andy'), ('D', 'David')], default='', max_length=100),
        ),
    ]
