# Generated by Django 2.0.2 on 2018-02-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_caselog_handleby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='handleby',
            field=models.CharField(choices=[('Andy', 'Andy'), ('David', 'David')], default='', max_length=100),
        ),
    ]
